-- Contenus de démarrage pour les quatre parcours jeune.
-- À exécuter après schema.sql dans Supabase > SQL Editor.
-- Le script peut être relancé : il met à jour les parcours/modules existants
-- sans toucher aux inscriptions ni à la progression des apprenants.

do $$
declare
  track_row record;
  module_row record;
  v_track_id uuid;
  v_module_id uuid;
  v_module_order smallint;
  module_data jsonb;
  module_id uuid;
  lessons jsonb;
begin
  for track_row in
    select * from (values
      (6::smallint, 8::smallint, 'Mes premiers pas sur Internet', 'Découvrir les écrans, protéger ses petits secrets et savoir à qui demander de l’aide.', 1::smallint),
      (9::smallint, 11::smallint, 'Je deviens gardien·ne de mes infos', 'Protéger ses comptes, réfléchir avant de partager et faire de bons choix en ligne.', 2::smallint),
      (12::smallint, 15::smallint, 'Je prends du recul, je garde le contrôle', 'Décrypter l’information, agir contre le cyberharcèlement et maîtriser son identité numérique.', 3::smallint),
      (16::smallint, 18::smallint, 'Le numérique au service de mes projets', 'Construire ses projets, exercer son esprit critique face à l’IA et protéger ses données.', 4::smallint)
    ) as tracks(age_min, age_max, title, description, sort_order)
  loop
    select id into v_track_id from public.learning_tracks
      where age_min = track_row.age_min and age_max = track_row.age_max
      order by created_at asc limit 1;

    if v_track_id is null then
      insert into public.learning_tracks(age_min, age_max, title, description, sort_order, status)
      values(track_row.age_min, track_row.age_max, track_row.title, track_row.description, track_row.sort_order, 'published')
      returning id into v_track_id;
    else
      update public.learning_tracks set title = track_row.title, description = track_row.description,
        sort_order = track_row.sort_order, status = 'published'
      where id = v_track_id;
    end if;

    if track_row.age_min = 6 then
      lessons := '[
        {"title":"Mon écran et moi","tag":"MES ÉCRANS","icon":"👀","description":"À quoi sert une tablette ? Comment faire une pause ?","lesson":["Un écran peut servir à apprendre, jouer, écouter une histoire ou parler avec quelqu’un.","Tes yeux et ton corps ont besoin de pauses. De temps en temps, pose l’écran, bouge et regarde au loin.","Si tu vois quelque chose qui te fait peur ou te rend triste, ferme l’écran et va le raconter à un adulte de confiance."],"question":"Pendant une vidéo, une image te fait peur et te met mal à l’aise. Que fais-tu ?","options":["Je continue à regarder en silence.","Je ferme l’écran et je vais en parler à un adulte de confiance.","Je l’envoie à un ami pour lui demander s’il a peur aussi."],"correct":1,"explanation":"Tu peux fermer l’écran et demander de l’aide. Tu n’as pas à gérer ça seul·e.","duration":"4 min"},
        {"title":"Mon secret magique","tag":"MES SECRETS","icon":"🔑","description":"Un secret qui protège ton compte et tes informations.","lesson":["Un mot de passe, c’est comme une clé magique qui protège tes affaires numériques.","Garde cette clé secrète. Ne la donne qu’à ton parent ou à l’adulte qui t’aide avec ton compte.","Si quelqu’un te demande ton mot de passe, ne réponds pas tout seul : demande de l’aide à un adulte de confiance."],"question":"Un joueur te demande ton mot de passe pour t’offrir des points. Que fais-tu ?","options":["Je lui donne vite pour gagner les points.","Je garde mon mot de passe secret et je demande conseil à un adulte.","Je lui donne seulement le début."],"correct":1,"explanation":"Un mot de passe reste secret, même quand on te promet un cadeau.","duration":"5 min"},
        {"title":"Je demande de l’aide","tag":"MES ADULTES DE CONFIANCE","icon":"💬","description":"Trouver les mots quand une chose en ligne nous dérange.","lesson":["Tu as le droit de dire stop, de fermer une page et de demander de l’aide.","Tu peux dire simplement : J’ai vu quelque chose qui m’a gêné·e. Est-ce que tu peux m’aider ?","Un adulte de confiance t’écoute et cherche une solution avec toi. Tu n’es pas en faute."],"question":"Quelqu’un écrit quelque chose qui te rend triste. Quel est le meilleur choix ?","options":["Je garde ça pour moi, j’ai peut-être fait une bêtise.","J’en parle à un adulte en qui j’ai confiance. Je ne suis pas en faute.","Je réponds avec un message encore plus méchant."],"correct":1,"explanation":"Un adulte de confiance peut t’écouter et t’aider sans te juger.","duration":"4 min"}
      ]'::jsonb;
    elsif track_row.age_min = 9 then
      lessons := '[
        {"title":"Un mot de passe solide","tag":"SÉCURITÉ","icon":"🔐","description":"Créer une phrase secrète difficile à deviner et facile à retenir.","lesson":["Un bon mot de passe est long, unique et difficile à deviner. Évite ton prénom, ta date de naissance ou 123456.","Une phrase de plusieurs mots que tu es seul·e à connaître est souvent plus facile à retenir et plus difficile à deviner.","Ne réutilise pas le même mot de passe partout et ne le partage jamais dans une conversation ou un jeu."],"question":"Quel mot de passe est le plus difficile à deviner ?","options":["adama2014","12345678","Une longue phrase secrète que je n’utilise nulle part ailleurs"],"correct":2,"explanation":"Une phrase longue et unique est plus difficile à deviner. Ne la partage jamais.","duration":"6 min"},
        {"title":"Qui se cache derrière l’écran ?","tag":"RENCONTRES EN LIGNE","icon":"🧭","description":"Réagir prudemment quand une personne inconnue nous écrit.","lesson":["Sur Internet, on ne peut pas toujours vérifier qui est vraiment derrière un profil.","Ne partage pas ton nom complet, ton adresse, ton école, ton numéro ou des photos privées avec une personne rencontrée en ligne.","Si quelqu’un insiste, demande une photo ou veut garder un secret avec toi, arrête la conversation et parle à un adulte de confiance."],"question":"Un nouveau contact veut savoir dans quelle école tu vas et te demande une photo. Que fais-tu ?","options":["Je lui réponds, il a l’air sympa.","Je ne partage pas ces infos, j’arrête la discussion et j’en parle à un adulte.","Je demande son école en échange."],"correct":1,"explanation":"Les informations sur ton école et tes photos sont personnelles. Un adulte de confiance peut t’aider.","duration":"7 min"},
        {"title":"Je laisse une bonne trace","tag":"VIE PRIVÉE","icon":"👣","description":"Comprendre ce qu’une photo ou un message révèle de nous.","lesson":["Une photo peut montrer plus que tu ne le penses : le lieu, l’école, un uniforme ou les personnes autour.","Avant de publier, demande-toi si tu serais à l’aise de revoir cette image plus tard.","Demande toujours l’accord d’un ami avant de partager une photo où il apparaît."],"question":"Tu veux publier une photo de ton ami. Quel est le bon réflexe ?","options":["Je la publie, puisqu’on est amis.","Je lui demande son accord et je vérifie qu’aucune info privée n’apparaît.","Je cache juste son visage."],"correct":1,"explanation":"Demander l’accord de ton ami protège sa vie privée et respecte son choix.","duration":"6 min"}
      ]'::jsonb;
    elsif track_row.age_min = 12 then
      lessons := '[
        {"title":"Info ou intox ?","tag":"ESPRIT CRITIQUE","icon":"🔎","description":"Vérifier une publication virale avant de la croire ou de la partager.","lesson":["Une publication très partagée n’est pas forcément vraie. Les titres choquants sont souvent conçus pour provoquer une réaction rapide.","Vérifie la date, l’auteur, la source originale et compare l’information avec au moins deux sources fiables.","Une image peut être sortie de son contexte. Cherche l’image ou les mots-clés avec le lieu et l’événement."],"question":"Un message alarmant annonce une fermeture d’écoles, sans source ni date. Quel est le premier bon réflexe ?","options":["Le partager à tous mes contacts au cas où.","Retrouver la source et la date, puis vérifier auprès de sources fiables.","Me fier au nombre de partages."],"correct":1,"explanation":"Vérifie l’origine, la date et plusieurs sources avant de partager une information urgente.","duration":"9 min"},
        {"title":"Face au cyberharcèlement","tag":"RESPECT EN LIGNE","icon":"🤝","description":"Soutenir une personne et signaler sans amplifier les attaques.","lesson":["Le cyberharcèlement, ce sont des attaques répétées en ligne qui font du mal. Ce n’est jamais la faute de la personne ciblée.","Ne transfère pas les messages humiliants. Soutiens la personne, conserve des preuves de manière sûre et signale les contenus.","Parle à un adulte de confiance. Si tu es ciblé·e, tu mérites de l’aide et tu ne dois pas affronter cela seul·e."],"question":"Un camarade est humilié dans une discussion de groupe. Comment peux-tu aider ?","options":["Transférer les captures à d’autres amis.","Le soutenir, garder une preuve sans la diffuser et signaler à un adulte.","Ne rien faire, pour ne pas être mêlé·e à l’histoire."],"correct":1,"explanation":"Soutenir la personne, ne pas amplifier les attaques et alerter un adulte aide à briser le silence.","duration":"10 min"},
        {"title":"Mon identité numérique","tag":"RÉPUTATION","icon":"🪪","description":"Choisir ce que les autres peuvent apprendre de nous en ligne.","lesson":["Tes publications, commentaires, photos et réactions contribuent à ton identité numérique.","Les paramètres de confidentialité aident, mais une capture d’écran peut circuler. Publie en pensant à ton futur toi.","Tu peux demander la suppression d’un contenu qui te concerne et solliciter l’aide d’un adulte pour faire un signalement."],"question":"Avant de publier une photo publique, quel réflexe est le plus prudent ?","options":["Vérifier l’audience, les détails visibles et si les personnes sont d’accord.","La publier vite avant de changer d’avis.","Penser que le mode privé empêche toute capture."],"correct":0,"explanation":"Vérifie ce que la photo révèle, qui peut la voir et l’accord des personnes présentes.","duration":"8 min"}
      ]'::jsonb;
    else
      lessons := '[
        {"title":"Construire mon profil pro","tag":"AVENIR & EMPLOI","icon":"💼","description":"Présenter ses compétences sans s’inventer un parcours.","lesson":["Un profil professionnel clair met en avant tes compétences, tes projets, tes expériences et ce que tu veux apprendre.","Choisis une adresse e-mail sobre, une photo appropriée et une présentation courte qui te ressemble.","Ne publie pas de données sensibles. Vérifie les paramètres de visibilité et sépare si besoin tes usages personnels et professionnels."],"question":"Tu n’as pas encore beaucoup d’expérience. Comment rendre ton profil intéressant ?","options":["Inventer un stage pour attirer l’attention.","Mettre en valeur des projets, compétences et ce que tu souhaites apprendre.","Publier toutes mes coordonnées pour être facilement joignable."],"correct":1,"explanation":"Les projets et compétences réels comptent. Tu peux présenter ton potentiel sans inventer d’expérience.","duration":"12 min"},
        {"title":"L’IA, avec esprit critique","tag":"INTELLIGENCE ARTIFICIELLE","icon":"✦","description":"Utiliser l’IA sans lui confier aveuglément son jugement.","lesson":["Une IA générative peut produire une réponse convaincante qui contient pourtant des erreurs ou des sources inventées.","Ne saisis jamais de données personnelles, de mots de passe, de dossiers confidentiels ou d’informations sensibles dans un outil public.","Vérifie les faits avec des sources fiables, indique quand tu as utilisé une IA et garde la responsabilité de ce que tu rends ou publies."],"question":"Une IA fournit une statistique avec une source que tu ne retrouves pas. Que fais-tu ?","options":["La citer, car elle paraît plausible.","Vérifier la source et la donnée avec des références fiables avant de l’utiliser.","Demander à l’IA de confirmer sa réponse."],"correct":1,"explanation":"Une IA peut inventer une référence. Vérifie directement les données dans des sources fiables.","duration":"10 min"},
        {"title":"Mon image, mes choix","tag":"AUTONOMIE NUMÉRIQUE","icon":"📱","description":"Reprendre la main sur ses données et ses usages.","lesson":["Passe régulièrement en revue les applications connectées à tes comptes, tes permissions et les informations visibles publiquement.","Active l’authentification à deux facteurs quand elle est disponible et garde une méthode de récupération sûre.","Tes choix numériques doivent te servir : coupe les notifications inutiles, vérifie les réglages et demande la suppression des données dont tu n’as plus besoin."],"question":"Une application demande l’accès permanent à tes contacts et à ta localisation. Que fais-tu ?","options":["J’accepte tout pour pouvoir continuer.","Je vérifie si c’est nécessaire et limite les permissions dans les réglages.","Je donne aussi accès à mes photos, comme ça tout fonctionne."],"correct":1,"explanation":"Accorde seulement les permissions nécessaires et reprends-les dans les réglages quand tu veux.","duration":"9 min"}
      ]'::jsonb;
    end if;

    lessons := lessons || '[
      {"title":"Mes données, mon choix","tag":"DONNÉES PERSONNELLES","level":"Découverte","icon":"🛡️","description":"Reconnaître les informations qui doivent rester privées.","lesson":["Une donnée personnelle est une information qui parle de toi : ton nom, une photo, ton adresse, ton école ou ton numéro.","Avant de remplir un formulaire ou d’envoyer une photo, regarde qui la demande et pourquoi.","Tu peux refuser de partager une information qui n’est pas nécessaire et demander conseil à un adulte."],"question":"Une application de jeu demande ton adresse et ton numéro de téléphone. Que fais-tu ?","options":["Je les donne pour débloquer le jeu.","Je vérifie si ces informations sont nécessaires et je demande conseil avant de les partager.","Je donne de fausses informations au hasard."],"correct":1,"explanation":"Les informations personnelles ne sont pas nécessaires à tous les services. Vérifie et demande conseil.","duration":"6 min"},
      {"title":"Mes droits et le respect en ligne","tag":"DROITS DE L’ENFANT","level":"Découverte","icon":"⚖️","description":"Comprendre que le respect et la protection continuent sur Internet.","lesson":["Tes droits existent aussi en ligne : être protégé·e, respecté·e et pouvoir demander de l’aide.","Publier une photo ou un message sur quelqu’un sans son accord peut lui faire du mal.","Si un contenu te met mal à l’aise, tu peux le signaler et en parler à une personne de confiance."],"question":"Quelqu’un partage une photo de toi sans ton accord. Quel réflexe adopter ?","options":["Je pense que je n’ai aucun droit sur cette photo.","Je demande le retrait, je garde une preuve et je sollicite un adulte si besoin.","Je republie une photo de cette personne en retour."],"correct":1,"explanation":"Tu peux demander le retrait du contenu et te faire accompagner pour le signaler.","duration":"7 min"},
      {"title":"Comment fonctionne Internet ?","tag":"INTERNET","level":"Intermédiaire","icon":"🌐","description":"Découvrir les traces, les liens et les échanges qui rendent le web possible.","lesson":["Internet relie des appareils et des services qui échangent des informations. Un site ou une application peut donc recevoir les données que tu y envoies.","Un lien peut mener vers un vrai site ou vers une copie conçue pour tromper. Regarde l’adresse avant de saisir un mot de passe.","Quand tu publies quelque chose, d’autres personnes peuvent le copier ou le garder. Réfléchis à l’audience avant de partager."],"question":"Un lien reçu dans un message te demande de te reconnecter à ton compte. Que vérifies-tu d’abord ?","options":["Le nom du site et son adresse, en ouvrant le service par son application ou son adresse habituelle.","Le logo, car il garantit que le site est vrai.","Le nombre d’emojis dans le message."],"correct":0,"explanation":"Un logo peut être copié. Vérifie l’adresse et passe par le service officiel que tu connais.","duration":"8 min"},
      {"title":"Info ou intox ?","tag":"ESPRIT CRITIQUE","level":"Intermédiaire","icon":"🔎","description":"Prendre le temps de vérifier une information avant de la partager.","lesson":["Un message urgent ou très surprenant peut chercher à provoquer une réaction rapide.","Cherche l’auteur, la date et la source d’origine. Compare avec plusieurs sources identifiables.","Une photo peut être ancienne ou sortie de son contexte. Vérifie où et quand elle a été prise."],"question":"Une publication affirme qu’un événement vient d’arriver, mais ne donne aucune source. Que fais-tu ?","options":["Je la partage immédiatement pour prévenir mes proches.","Je cherche la source, la date et une confirmation indépendante.","Je la crois si beaucoup de personnes l’ont aimée."],"correct":1,"explanation":"Le nombre de réactions ne prouve pas qu’une information est vraie. Recoupe-la avant de la partager.","duration":"8 min"},
      {"title":"Signaler pour protéger","tag":"PLATEFORMES DE SIGNALEMENT","level":"Intermédiaire","icon":"🚩","description":"Savoir quoi faire face à un contenu dangereux ou à une situation inquiétante.","lesson":["Les plateformes proposent souvent des outils pour bloquer un compte ou signaler un contenu.","En cas de menace ou de harcèlement, ne réponds pas par une attaque. Garde les éléments utiles sans les repartager.","Parle à un adulte de confiance. Un signalement ne remplace pas l’aide d’une personne qui peut agir près de toi."],"question":"Tu reçois des messages menaçants qui reviennent. Quel est le bon plan ?","options":["Répondre par une menace plus forte.","Garder les preuves sans les diffuser, bloquer et signaler, puis en parler à un adulte.","Supprimer tout et ne jamais en parler."],"correct":1,"explanation":"Conserver les éléments, utiliser les outils de signalement et demander de l’aide permet d’agir sans amplifier la situation.","duration":"9 min"},
      {"title":"Réseaux sociaux : mes choix","tag":"RÉSEAUX SOCIAUX","level":"Expert","icon":"📱","description":"Garder la maîtrise de son audience, de son temps et de ses publications.","lesson":["Les recommandations et notifications sont conçues pour te faire revenir. Tu peux choisir tes limites et désactiver ce qui te distrait.","Un compte privé réduit l’audience, mais ne garantit pas qu’une publication ne sera jamais copiée.","Vérifie régulièrement les personnes qui voient tes contenus, les applications liées et les permissions demandées."],"question":"Tu veux publier une vidéo avec des amis dans un lieu reconnaissable. Que fais-tu avant ?","options":["Je la publie tout de suite si mon compte est privé.","Je demande leur accord, vérifie les détails révélés et choisis l’audience adaptée.","Je tague tout le monde pour que la vidéo circule mieux."],"correct":1,"explanation":"L’accord des personnes et les détails visibles comptent, même sur un compte privé.","duration":"9 min"},
      {"title":"L’intelligence artificielle au quotidien","tag":"INTELLIGENCE ARTIFICIELLE","level":"Expert","icon":"✦","description":"Utiliser l’IA avec curiosité, prudence et esprit critique.","lesson":["Une IA peut aider à trouver des idées ou reformuler un texte, mais elle peut aussi se tromper ou inventer des informations.","Évite de lui confier des mots de passe, des photos privées ou des informations permettant d’identifier une personne.","Vérifie les faits avec des sources fiables et garde la responsabilité de ce que tu rends ou publies."],"question":"Une IA donne une réponse convaincante avec une référence que tu ne retrouves pas. Que fais-tu ?","options":["Je l’utilise, le ton paraît sûr.","Je vérifie la référence dans des sources fiables et je n’envoie aucune donnée personnelle.","Je demande à la même IA de garantir sa réponse."],"correct":1,"explanation":"Une IA peut produire des références inventées. Vérifie la source directement.","duration":"10 min"},
      {"title":"Glossaire des mots essentiels","tag":"GLOSSAIRE","level":"Découverte","icon":"📖","description":"Apprendre le vocabulaire pour mieux comprendre le numérique.","lesson":["Une donnée personnelle est une information qui permet de reconnaître ou de contacter une personne.","Le hameçonnage est un message trompeur qui cherche à voler des informations ou à prendre le contrôle d’un compte.","L’empreinte numérique correspond aux traces que l’on laisse en utilisant des services en ligne."],"question":"Un message imite une banque et te demande ton code secret. Comment appelle-t-on souvent cette tromperie ?","options":["Un hameçonnage.","Une mise à jour.","Un glossaire."],"correct":0,"explanation":"Le hameçonnage essaie de tromper une personne pour lui voler des informations ou un accès.","duration":"5 min"}
    ]'::jsonb;

    for module_row in select lesson.value, lesson.ordinality from jsonb_array_elements(lessons) with ordinality as lesson(value, ordinality)
    loop
      module_data := module_row.value;
      v_module_order := module_row.ordinality;
      select m.id into v_module_id from public.modules as m
        where m.track_id = v_track_id and m.title = module_data ->> 'title'
        order by created_at asc limit 1;

      if v_module_id is null then
        insert into public.modules(track_id, title, summary, content, estimated_minutes, sort_order, status)
        values(v_track_id, module_data ->> 'title', module_data ->> 'description', module_data,
          nullif(regexp_replace(module_data ->> 'duration', '[^0-9]', '', 'g'), '')::smallint,
          v_module_order, 'published')
        returning id into v_module_id;
      else
        update public.modules set summary = module_data ->> 'description', content = module_data,
          estimated_minutes = nullif(regexp_replace(module_data ->> 'duration', '[^0-9]', '', 'g'), '')::smallint,
          status = 'published'
        where id = v_module_id;
      end if;
      v_module_id := null;
    end loop;
    v_track_id := null;
  end loop;
end $$;

-- Vérification rapide : doit retourner 4 parcours et 11 modules publiés par parcours.
select t.title, t.age_min, t.age_max, count(m.id) as modules_publies
from public.learning_tracks t
left join public.modules m on m.track_id = t.id and m.status = 'published'
where (t.age_min, t.age_max) in ((6,8),(9,11),(12,15),(16,18))
group by t.id, t.title, t.age_min, t.age_max
order by t.age_min;
